version: '3'

services:
  db:
    container_name: db
    image: postgres:14
    environment:
      - POSTGRES_USER=EuphoriaV
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=wechat
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "wechat" ]
      interval: 30s
      timeout: 60s
      retries: 5

  wechat:
    container_name: wechat
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - WECHAT_HOST=db
      - WECHAT_USERNAME=EuphoriaV
      - WECHAT_PASSWORD=1234

volumes:
  postgres: