spring:
  application:
    name: wechat
  datasource:
    url: jdbc:postgresql://localhost:5432/wechat
    username: EuphoriaV
    password: ${WECHAT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none