spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mariadb://localhost/wechat?useUnicode=true&characterSetResults=UTF-8&characterEncoding=UTF-8&serverTimezone=Europe/Moscow
spring.datasource.username=root

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true

spring.freemarker.suffix=.ftlh
server.error.whitelabel.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
server.error.path=/error